### ISSUE TITLE
Create new "Data Binding" chapter in the spec

### ISSUE THREAD

**Issue by chkal** [mvc-spec/mvc-spec#101]
We should remove the "Exception Handling" chapter and replace it with a "Data Binding" chapter. IMO this makes sense because there is nothing special about the exception handling in MVC. We simply use the JAX-RS features. But data binding and validation works totally different for MVC controllers.

A few notes about the content of the new chapter:
* Controllers are always executed, even if there are binding or validation errors
* Details about errors are available via `BindingResult`
* Implementations should warn the developer if there are binding errors but `BindingResult` was not "consumed"
* Bound values are only validated if the binding was successful
* If the binding fails for some reason (like invalid number format), the binding will be result in a default value (null, false, 0, etc).

**Comment by chkal** [comment]
No need for any help. I'm already working on that. But thanks a lot!

**Comment by chkal** [comment]
If you have some time and would like to help, have a look at the "help wanted" labels for the spec and Ozark.

**Comment by Daniel-Dos** [comment]
wonderful .   :   )

**Comment by chkal** [comment]
Perhaps you could have a look at mvc-spec/ozark#168 and/or mvc-spec/ozark#169. In both cases I'm actually more or less sure that it is an CXF issue which should be reported with some simple reproducer application.
