### ISSUE TITLE
Describe how configuration works in MVC

### ISSUE THREAD

**Issue by chkal** [mvc-spec/mvc-spec#104]
We are currently using the JAX-RS configuration mechanism for configuration without describing this in the spec. This should be mentioned explicitly.

To open up for other ways of configuring MVC implementations, we should mention that implementations MUST support JAX-RS configuration properties but MAY support other ways. This opens the door for integrating with Microprofile Config and others in the future.

**Comment by chkal** [comment]
Sure. I think "Configuration" could be a new section in the "Application" chapter, because it describes an application level concern.

Basically I think that we need to describe how MVC implementations are configured. There are only a few configuration settings which are defined in the spec. For example the CSRF mode. Users can configure this by providing corresponding properties in `Application.getProperties()` like shown [here](https://github.com/mvc-spec/ozark/blob/0fb00bd912d63cbae032e5335ce74c43ace3ea55/test/csrf-property/src/main/java/org/mvcspec/ozark/test/csrfproperty/MyApplication.java#L42-L47).

AFAIK this isn't explicitly described in the spec at the moment. And it would be cool to leave the door open for using other configuration sources like [JSR 382](https://www.jcp.org/en/jsr/detail?id=382). So we could add something like:

> Implementations MUST support configuration via the native JAX-RS configuration mechanism but MAY support other configuration sources.

**Comment by Daniel-Dos** [comment]
@chkal, closed this issue . #157
