### ISSUE TITLE
javax.mvc.event.AfterControllerEvent

### ISSUE THREAD

**Issue by kmohanarangam** [mvc-spec/mvc-spec#125]
AfterControllerEvent is fired after a controller returns successfully. If the controller throws an exception, this event may not be fired.
This might cause issues when the application wants to collect stats of failed requests count. Is it possible to add one more event that'll fire no matter how the controller executes or is there a suggestion on how to  handle this scenario?

**Comment by chkal** [comment]
A few notes regarding this topic:

@kmohanarangam I agree that there should be a way to distinguish the success from the error case. But I don't think that another event type is necessary for that. Perhaps we could add something like `AfterControllerEvent#getException()` if we decide to change the current behavior.

Another thing to note: I just checked the the Ozark code. And to me it looks like the event is currently fired for ALL requests, even if the controller threw an exception. See the corresponding code in `ViewResponseFilter`:

https://github.com/mvc-spec/ozark/blob/0299508224ed7f684773c8e091f44f9691169f82/core/src/main/java/org/mvcspec/ozark/core/ViewResponseFilter.java#L98-L110

AFAIK a container response filter is executed even if the resource threw an exception. In this case Ozark would currently violate the spec requirement.

@kmohanarangam Did you verify the behavior with Ozark a was your comment just from reading the Javadocs of the spec?

**Comment by kmohanarangam** [comment]
I didn't check the Ozark code. My comment was based on specification document. Well, it looks like Ozark violates the current spec requirement. So one of them has to be changed. Thanks for clarifying.
AfterControllerEvent#getException() would also work.

**Comment by chkal** [comment]
Ok, thanks! We will have a deeper look at this issue.

**Comment by kmohanarangam** [comment]
@chkal how can I help?

**Comment by chkal** [comment]
@kmohanarangam I'm currently working on the TCK and will write the corresponding tests for the events section next week. So I'll dig deeper into this very soon.

**Comment by chkal** [comment]
I agree that firing the event even in case of controller failures is the best way to go. So I created #193 to adjust the API docs and the spec document for both `AfterControllerEvent` and `AfterProcessViewEvent`.

One additional note: Currently Ozark does NOT fire the even in case of errors. So we need to adjust Ozark to support this case. I'll create a separate issue to track this as soon as #193 is merged.
