### ISSUE TITLE
Discuss whether we really need three MvcContext.get*Path() methods

### ISSUE THREAD

**Issue by chkal** [mvc-spec/mvc-spec#151]
There are currently three methods on `MvcContext` to get different paths:

1. `getContextPath()`
2. `getApplicationPath()`
3. `getBasePath()`

We should discuss whether we really need all three methods. My thoughts:

1. The context path may be useful, but for JSP and Facelets you can use `#{request.contextPath}` instead. So this method is actually only useful for 3rd party view engines. And it only makes sense in Servlet environments. 
2. This method isn't really useful alone. You usually need the context path too. But in this case you could also use `getBasePath()`.
3. This one is the only one I think we should really keep.

Thoughts?

**Comment by Daniel-Dos** [comment]
Hi @chkal,

keep only the `getBasePath()` , would work well for 3rd ViewEngine?

**Comment by chkal** [comment]
I always use `getBasePath()` because this one is useful if you link to other controllers. As mentioned before `getContextPath()` may also be useful for 3rd party view engines which don't provide a builtin way to access the `HttpServletRequest`.

**Comment by chkal** [comment]
I agree. My updated thoughts about the methods:

* `getContextPath()`: Not really required. JSP and Facelets can use `${request.contextPath}` and 3rd party view engines should actually store the `HttpServletRequest` in the model if the template engine doesn't provide a native way to access the context path, in which case something like `${request.contextPath}` will also work. And actually `${mvc.contextPath}` is the only method left which assumes a Servlet environment. So I think we should remove it.
* `getApplicationPath()`: This one is actually never really useful without adding the context path in which case people can use `getBasePath()` instead. So let's remove this too.
* `getBasePath()`: This method is really useful for linking to other controllers or JAX-RS resource methods. So we should definitely keep it.

Thoughts?

**Comment by chkal** [comment]
This got fixed with #158

**Comment by chkal** [comment]
I just discovered that some of my assumptions mentioned in the original issue were actually incorrect.

> The context path may be useful, but for JSP and Facelets you can use `#{request.contextPath}` instead. 

That's actually not entirely correct. For JSF you can use `#{request.contextPath}`, but for JSP `request` isn't avaiable as an implicit variable in the EL context. For JSP you have to use `${pageContext.request.contextPath}`.

Sorry about that.
