### ISSUE TITLE
Reduce font size for source code in spec document

### ISSUE THREAD

**Issue by chkal** [mvc-spec/mvc-spec#152]
We are including the source of some classes in the spec document. Especially in the "Events" and "View Engines" chapters.

Unfortunately the font size seems to be so huge, that we get ugly line breaks. See this screenshot:

![Screenshot](https://i.imgur.com/AeG6Tz0.png)

It would be great if we could reduce the font size so that typical classes can be included without getting such line breaks.

Any help with this is welcome!

**Comment by Daniel-Dos** [comment]
Hi @chkal , 
I was able to do decrease font size for that code. What do you think is interesting?

**Comment by chkal** [comment]
Awesome! Thanks! I'll review #160 later today.

**Comment by Daniel-Dos** [comment]
@chkal , closed this issue .   :  )

**Comment by chkal** [comment]
Thanks. Forgot to close it after the merge.
