### ISSUE TITLE
Where to put configuration key constants

### ISSUE THREAD

**Issue by chkal** [mvc-spec/mvc-spec#154]
Currently the constants for configuration keys are spread over different classes. For example:

* `javax.mvc.engine.ViewEngine.VIEW_FOLDER`
* `javax.mvc.security.Csrf.CSRF_PROTECTION`
* more?

Does this make sense? Usually there is as single class which defines the constants for all the supported configuration entries.

We should discuss this.

**Comment by Daniel-Dos** [comment]
I think it is interesting to have a class that contains only those constants and other ones concentrates in only one point.

**Comment by chkal** [comment]
I see pros and cons for both ways to do it. Having all constants on a single class makes them easier to find. Currently you have to remember on which class the different constants are.

**Comment by lefloh** [comment]
I usually prefer placing constants at the class where they belong to but I can see the value of a complete overview of all public configuration properties for a developer. Could using documentation like e.g [Spring Boot's Constant Field Values](https://docs.spring.io/spring-boot/docs/current/api/constant-values.html) be an alternative?

**Comment by chkal** [comment]
Interesting. Is this a standard Javadoc feature?

**Comment by chkal** [comment]
I did not know it either. :laughing:

**Comment by ivargrimstad** [comment]
I would also rather keep the constants where they belong rather than having some universal constant class...

**Comment by chkal** [comment]
Looks like a majority likes to keep the constants in the corresponding classes. So I'll close this one now. Thanks for sharing your thoughts on this.
