### ISSUE TITLE
Constants for ViewEngine ordering

### ISSUE THREAD

**Issue by chkal** [mvc-spec/mvc-spec#169]
Hi all,

we currently have the following priority constants for using `@Priority` with the `ViewEngine` interface:

* **DEFAULT** (1000): built-in view engines (JSP, Facelets)
* **FRAMEWORK** (2000): 3rd party view engines (like Ozark extensions)
* **APPLICATION** (3000): application-provided view engines

Please note that higher integer values mean that the view engine is executed first. And please note that priorities are only relevant if multiple view engines return `true` for `ViewEngine.supports(name)`. 

I'm basically fine with using these categories. And the priority values make sense to me: View engines provided by the application developer are preferred over all others. And 3rd party view engines have higher priority than the built-in ones. 

There are just two things I would like to discuss:

 * The priority `DEFAULT` seems to be named this way not because it is the **default priority**, but because it is the priority for the **default view engines** (JSP + Facelets). Maybe this is a bit misleading?
* Currently view engines without `@Priority` are treated as having an implicit `DEFAULT` priority. So by default, view engines get a very low priority, which is the same as the built-in ones. I wonder if this is a good default. Usually built-in and 3rd party view engines will be created by people familiar with MVC and will most likely get an explicit priority. But I think it is very likely that application developers forget about `@Priority` and then get a very low priority although they are actually in the `APPLICATION` category.

So I think we **could** do the following things:

* Renamed `DEFAULT` to `BUILTIN` to make it more explicit, that the priority is for the standard engines.
* Change the default priority to `APPLICATION` so view engines without priority will usually be preferred due to the high priority value.

To be honest, I'm not sure if these change are a really good idea. I just would like to share my thoughts and hear what @mvc-spec/expert-group things.

**Comment by lefloh** [comment]
I’m absolutely not strong on this one but this is confusing if you compare it with [`javax.ws.rs.Priorities`][1]?

MVC:  
>Otherwise, sort the resulting set in descending order of priority using the integer value from the @Priority annotation …

JAX-RS:
>…the lower the number the higher the priority…

Anyway, I also think that `APPLICATION` should be the default and win. Renaming `DEFAULT` to `BUILTIN` makes also sense.

[1]: https://github.com/jax-rs/api/blob/34eb34b40a536ffeae9378d05a9d704527b1aae1/jaxrs-api/src/main/java/javax/ws/rs/Priorities.java

**Comment by chkal** [comment]
> I’m absolutely not strong on this one but this is confusing if you compare it with javax.ws.rs.Priorities?

Yeah, this is confusing. I didn't notice this difference. Could you file a separate issue for that?

**Comment by ivargrimstad** [comment]
I think there is a mix of the two approaches spread all over the platform. For security, the lower number takes precedence. In MicroProfile Config it is the other way around. 

I guess that as long as we document it properly we can do either way.

**Comment by chkal** [comment]
> think there is a mix of the two approaches spread all over the platform.

Ok. I wasn't aware of that. In this case I'm not strong on aligning with JAX-RS in the regard.

**Comment by lefloh** [comment]
Me neither.

**Comment by chkal** [comment]
@ivargrimstad What do you think about renaming `DEFAULT` to `BUILTIN` and making `APPLICATION` the default? See my reasoning in the issue description.

**Comment by chkal** [comment]
I think we all agree that whether we use increasing or decreasing priority ordering doesn't matter too much, because this is mixed in the platform anyway.

But what about renaming `DEFAULT` to `BUILTIN` and making `APPLICATION` the default. @lefloh and I seem to like the idea. What do others say? @ivargrimstad? @Daniel-Dos? @mvc-spec/expert-group?

**Comment by Daniel-Dos** [comment]
Hi all,

+1 for rename `DEFAULT` to `BUILTIN` and  `APPLICATION` the default.

**Comment by chkal** [comment]
I just created #191 to update the API as discussed.
