### ISSUE TITLE
Should RedirectScope be a passivating scope?

### ISSUE THREAD

**Issue by chkal** [mvc-spec/mvc-spec#175]
I was a bit surprised to see that `@RedirectScoped` is a passivating scope. From the CDI javadocs:

> A bean is called passivation capable if the container is able to temporarily transfer the state of any idle instance to secondary storage. A passivating scope requires that beans with the scope are passivation capable.

Does this make sense? Requiring all redirect-scoped beans to be passivation capable is a weird requirement in the context of MVC.

Thoughts?

**Comment by chkal** [comment]
At least I don't know why passivation could be good idea for this scope. The lifetime of the scope is typically only a few hundert milliseconds. But maybe I'm missing something. 

@spericas @manfredriem @mnriem Any thoughts?

**Comment by manfredriem** [comment]
I think it is because if the scope is not passivation capable the implementation cannot use the session as its backing store.

**Comment by chkal** [comment]
Thanks, @manfredriem. At first, it seemed weird that the redirect scope needs to support passivation, because the scope's lifetime is typically just a few hundred milliseconds. But using the session scope as a backing store is a natural choice which also works well if you distribute sessions in a cluster.

So, if nobody disagrees, I'll close this issue in the next days.
