### ISSUE TITLE
Using @CsrfValid on class level

### ISSUE THREAD

**Issue by chkal** [mvc-spec/mvc-spec#176]
The API docs if the `@CsrfValid` annotation contains the following note:

> Even though this annotation is also targeted to {@code TYPE}, it can only be used to decorate individual controller methods.

Why is that? Is there a technical reason for this? It would be nice to also allow this on classes.

**Comment by lefloh** [comment]
No idea. Allowing this technically but disallowing it in the documentation is really weird.

**Comment by chkal** [comment]
I guess the annotation is allowed on type level for the interceptor binding. IIRC the feature is implemented as a CDI interceptor.

**Comment by chkal** [comment]
@spericas Could you share some thoughts on this? I just checked that and `@CsrfValid` isn't used on type level for the interceptor binding.

**Comment by spericas** [comment]
@chkal I would think it is because of interceptors. Perhaps the RI does not take advantage of that anymore, but may still be useful for other implementations.

**Comment by chkal** [comment]
@spericas Thanks for your feedback. I guess you are right. `@CsrfValid` is annotated with `@NameBinding`:

https://github.com/mvc-spec/mvc-spec/blob/e6a1764e0baf7cb5800bc58aa581365ae98db009/api/src/main/java/javax/mvc/security/CsrfValid.java#L47-L53

I guess it is safe to use `@NameBinding` on such annotations in case implementations want to use JAX-RS providers for the implementation. I'm just wondering if MVC annotation shouldn't also be annotated with CDI's `@InterceptorBinding` for consistency.

**Comment by chkal** [comment]
Please see #195 for the proposed changes
