### ISSUE TITLE
Better name for @CsrfValid?

### ISSUE THREAD

**Issue by chkal** [mvc-spec/mvc-spec#180]
Hi all,

I'm pretty sure you all start hating me now, but what about finding a better name for `@CsrfValid`? I don't like that name. It's confusing. Using the term "valid" in context of CSRF (which is actually the name of the attack we are trying to prevent) feels weird. You also wouldn't name an annotation `@SessionHijackingValid` or `@CrossSiteScriptingValid`.

Naming is hard, but what about:

 * `@CsrfProtected`
 * `@CsrfProtection`
 * `@CsrfTokenRequired`
 * `@CsrfVerified`
 * `@CsrfVerifciation`

Any other ideas? Please note that you only need this annotation when setting `Csrf.CSRF_PROTECTION` to `CsrfOptions.EXPLICIT`.

**Comment by Daniel-Dos** [comment]
Hi,

I like the new names +1 .

**Comment by lefloh** [comment]
I agree: `@CsrfProtected` sounds better!

**Comment by chkal** [comment]
If you all like `@CsrfProtected`, I'll create a pull request in the next days.

**Comment by chkal** [comment]
I just created #190 which renamed `@CsrfValid` to `@CsrfProtected`. Please review and approve.

While working on this I saw that we also have `CsrfValidationException`. Does anyone think that we also need to rename this one? Perhaps `CsrfProtectionException`? Not sure if this is really necessary. Thoughts?

**Comment by lefloh** [comment]
Don't think that renaming `CsrfValidationException` is necessary.

**Comment by ivargrimstad** [comment]
+1 for @CsrfProtected
