### ISSUE TITLE
Do we really need MvcEvent.getId()

### ISSUE THREAD

**Issue by chkal** [mvc-spec/mvc-spec#182]
All CDI events provided by MVC extend a base interface `MvcEvent`. This event has only a single method called `getId()`.

https://github.com/mvc-spec/mvc-spec/blob/e6a1764e0baf7cb5800bc58aa581365ae98db009/api/src/main/java/javax/mvc/event/MvcEvent.java#L18-L33

I already mentioned in 2015 that I don't see any use case for the `getId()` method. So I wonder how other feel about that. Back then there wasn't much discussion about this method. So maybe we should discuss this now.

What do you think? Should we keep it? How could it be used? Should we drop it? If so, should we keep an empty `MvcEvent` interface?

**Comment by Daniel-Dos** [comment]
Hi, 

I agreed with you, not see use for getId(), in implementation he return only an new Date formatted.

in case the drop, think you should remove the class too.

**Comment by lefloh** [comment]
I wouldn't fight for it ;-) 
If we keep it I'd like to discuss why it doesn't need to be universally unique.
Using the `MvcEvent` interface for all MVC events makes sense in my eyes.

**Comment by chkal** [comment]
I agree. Such IDs usually only make sense if they are unique.
