### ISSUE TITLE
Simplify BindingError interface

### ISSUE THREAD

**Issue by chkal** [mvc-spec/mvc-spec#186]
We recently created a new base interface `ParamError` for both `ValidationError` and `BindingError`. Please see  #170 for the corresponding pull request.

This new interface now allows us to dramatically simplify the `BindingResult` interface. `BindingResult` currently looks like this:

```java
public interface BindingResult {

    // common methods for all error types
    boolean isFailed();
    List<String> getAllMessages();

    // special getter for binding errors
    Set<BindingError> getAllBindingErrors();
    BindingError getBindingError(String param);

    // special getter for validation errors
    Set<ValidationError> getAllValidationErrors();
    Set<ValidationError> getValidationErrors(String param);

}
```

I don't think that having these special methods for obtaining only binding or only validation errors make much sense any more. Actually they only exist, because we didn't had a base interface back then. 

What about this:

```java
public interface BindingResult {

    // keep these methods
    boolean isFailed();
    List<String> getAllMessages();

    // new methods returning ParamError base interface
    Set<ParamError> getAllErrors();
    Optional<ParamError> getError(String param);

}
```

So basically we removed the special methods for binding error and validation error (which BTW I never saw anyone using) and add new methods which work for both types as they return the base interface `ParamError`. If you want more specific information about the error, you can simply narrow down the type and get the information from `ValidationError` or `BindingError`. However, most information is available for both types from the `ParamError` interface.

BTW: We could even think about removing `getAllMessages()`, because it is exactly the same as `getAllErrors().stream().map(ParamError::getMessage).collect(Collectors.toSet())`. However, I guess we could also keep this method for providing as simple way to get all the messages.

What do you think? I want to get your feedback before I start to work on a pull request.

**Comment by chkal** [comment]
Hey @lefloh! Thanks a lot for your comment. I think I can explain this one.

In theory people can define multiple constraints on a single field/parameter. So a single value could also violate multiple constraints. Therefore, Bean Validation supports this case. So a `ConstraintViolationException` can actually contain multiple `ConstraintViolation` instances (see the method `ConstraintViolationException#getConstraintViolations()` and the [API docs](https://docs.oracle.com/javaee/7/api/javax/validation/ConstraintViolationException.html#getConstraintViolations--)).

Back then when we created `BindingResult` I thought it may be a good idea to support this case too. That's why `getValidationErrors` returns a set and not a single `ConstraintViolation`. However, I'm not sure if this was a good idea. It makes the API harder to use. And having more than one violation is EXTREMELY rare.

Therefore, my idea was that we should simplify the API and let `getError(String param)` return just an `Optional<ParamError>`. I think that's fine as long as this is documented. So if there is more than one violation, the method would simply return the first one. If people really want to get more than one, they can simple use `getAllErrors().filter( e -> e.getParam() == "someName")` instead. But the most common case, which is having either no or a single violation, is much easier to use.

Does this make sense?

**Comment by lefloh** [comment]
I understand that it's easier to use but I'm unsure if I like it :wink: 
I'm also unsure if multiple errors per field is really extremely rare. 
The question is what people expect and if they want to use multiple errors per field. If yes it get's more complicated especially within a template.

**Comment by chkal** [comment]
> I'm also unsure if multiple errors per field is really extremely rare.

That is a really good question. I also thought quite some time about that. I tried to make up some example where multiple constraint violations could make sense. But I didn't find a good example. Of course, you can mix `@Email` with `@Pattern`, but this usually don't make much sense.

Perhaps @gunnarmorling can help? Are there common cases for which multiple constraint violations can occur? Or is it really rare special case to have more than one violation.

> The question is what people expect and if they want to use multiple errors per field. If yes it get's more complicated especially within a template.

I think they would expect zero or exactly one error per field. But I may be wrong about that.

**Comment by gunnarmorling** [comment]
Hey, it's definitely to be expected that there are multiple constraint violations for a single field; a typical example could be a `@Size` constraint combined with `@Email`. So having a method that just returns a single violation or error would be not a good match, esp. as by default there's no ordering of constraints on a single field implied (the BV methods return a `Set`), so you wouldn't have a reliable way to return the "first one" or something similar.

**Comment by chkal** [comment]
@gunnarmorling Thanks for sharing your thoughts. I agree that multiple violations are common in case of container components. But I was thinking more about simple types like `String`, `long`, `double`, etc which are more commonly used when binding JAX-RS parameters. However, after thinking about this more, I guess that multiple violations for "simple" types are more likely to occur in real world apps when people start creating custom constraints. Like `@Size(min=8) @CharClasses(min=2)` for a password. So we should definitely support this case.

@lefloh So I guess you are right and we should definitely allow to get the set of violations for a specific parameter. What do you think about this:

```java
public interface BindingResult {

    // keep these methods
    boolean isFailed();
    List<String> getAllMessages();

    // new methods returning ParamError base interface
    Set<ParamError> getAllErrors();
    Set<ParamError> getErrors(String param);
    Optional<ParamError> getFirstError(String param);

}
```

So `getErrors(param)` would return a set just like discussed above. And we could also provide `getFirstError(param)` which people can use if they only want a single error (or none), because they either know that there cannot be more than one violation or because the UI component for displaying the error in the page only supports a single message. To get a deterministic "first error", we could sort the violations by some criterion so that people get consistent results when calling the method.

If you all like this idea, I could provide a pull request.

**Comment by lefloh** [comment]
I'm fine with the one-error method as long as there's clearly documented that this method may swallow errors but may be easier to use if the developer doesn't care (or knows what he's doing).

**Comment by chkal** [comment]
@gunnarmorling Thanks for your feedback.

Maybe you are correct. The method `getFirstError(param)` would basically be something like `getErrors(param).stream().findFirst()`. I just thought that `getFirstError()` could make some garantees about which error is returned if there is more than one. But this may not be super important. So maybe we should omit this method `getFirstError()` in the first version of the API.

Regarding `List<String> getAllMessages()`: IIRC this was done because in theory it is possible that multiple `ParamError` instances return the same value for `ParamError#getMessage()`. So duplicates are actually possible.

BTW: Talking about convenience methods. Actually `getAllMessages()` is the same as `getAllErrors().stream().map(ParamError::getMessage).collect(Collectors.toList())`. So maybe we should even remove this one?

**Comment by chkal** [comment]
Just a quick update on this. According to the discussion above, the `BindingError` interfaces would look like this:

```java
public interface BindingResult {

    // keep these methods
    boolean isFailed();
    List<String> getAllMessages();

    // new methods returning ParamError base interface
    Set<ParamError> getAllErrors();
    Set<ParamError> getErrors(String param);

}
```

So if you agree, I'll create a pull request this weekend.

PS: We could still discuss if we want to keep `getAllMessages()` or not.

**Comment by chkal** [comment]
Please see #192 for the corresponding pull request.
