### ISSUE TITLE
Renaming MvcUriBuilder interface

### ISSUE THREAD

**Issue by chkal** [mvc-spec/mvc-spec#188]
This is the last class I would like to discuss regarding naming. 

Back then we called our url builder `MvcUriBuilder`. IIRC this was mostly motivated by the fact that JAX-RS already contains an interface called `UriBuilder`. During my review of the interface I noticed that the builder actually doesn't contain anything MVC specific. So I wonder if the `Mvc*` prefix is a good idea. 

Actually the difference from the JAX-RS `UriBuilder` is that it already encapsulates a full URI template and then allows a *fluent* way of setting the URI template placeholders. So I was wondering if something like `FluentUriBuilder` would be a better name.

I actually don't like very much that we are using the `Mvc*` class name prefix so often. We tend to use it if we don't better names for something. :laughing:

**Comment by lefloh** [comment]
Yes, the name collision with `javax.ws.rs.core.UriBuilder` was the reason for the prefix.
I also don't like it but have no better idea so I'm fine with `FluentUriBuilder`.

Could accepting the name collision also be an option? I think it's not so dramatic here because this interface isn't intended for standalone use. We only expose it via `MvcContext#uriBuilder`. Maybe confusing but impossible to use the wrong import.

**Comment by chkal** [comment]
> Yes, the name collision with javax.ws.rs.core.UriBuilder was the reason for the prefix.
> I also don't like it but have no better idea so I'm fine with FluentUriBuilder.

Thanks! I also prefer `FluentUriBuilder` over `MvcUriBuilder`. But any other suggestions are welcome.

> Could accepting the name collision also be an option? I think it's not so dramatic here because this interface isn't intended for standalone use. We only expose it via MvcContext#uriBuilder. Maybe confusing but impossible to use the wrong import.

Not sure about that. People may still import the wrong class. And I guess people may want to assign the builder to local variables if they want to dynamically add query parameters to the URL. So I would prefer to find a class name that is different from `UriBuilder` to work around any confusion.

**Comment by mkarg** [comment]
I do not have the history, but do you actually need your own URI builder at all? JAX-RS 2.2-SNAPSHOT just adopted a PR which allows to build a URI from scratch (without a template).

**Comment by chkal** [comment]
In our case we are providing a builder which allows a fluent way to specify all the parameter values for a fixed URI template:

```java
URI uri = mvcContext.uriBuilder( "bookDetails" )  // @UriRef("bookDetails") on controller
         .set("isbn", 321321321312)               // @PathParam("isbn")
         .set("lang", "de")                       // @QueryParam("lang")
         .build();
```

The JAX-RS builder only allows to specify the parameter values in the `build()` method. So basically the JAX-RS builder provides a fluent way to create the URI template and then requires you to fill the values in a single step. 

Our builder doesn't allow to change the URI template at all. The template is fixed, because you ask MVC for a builder for a specific controller method. So the builder just provides a nice fluent way to specify all the parameter values.

**Comment by chkal** [comment]
I just had another look at the JAX-RS `UriBuilder` interface. Looks like the class provides a few more method than I knew about.

If I read it correctly, the builder also allows a fluent way to specify parameter values from a fixed template. If we would return JAX-RS's `UriBuilder` instead, the code could look like this:

```java
URI uri = mvcContext.uriBuilder( "bookDetails" )  // @UriRef("bookDetails") on controller
         .resolveTemplate("isbn", 321321321312)   // @PathParam("isbn")
         .replaceQueryParam("lang", "de")         // @QueryParam("lang")
         .build();
```

@lefloh I don't remember the discussions we had back then in detail anymore. But basically it looks like the JAX-RS `UriBuilder` actually provides everything we need. Or am I missing something here?

**Comment by lefloh** [comment]
Our goal was an easy way to create URIs from within a template. The JAX-RS `UriBuilder` is a bit verbose for templates and not all methods are supported by template engines (Class as parameter, varargs, etc.). We wanted something like this:

`${mvc.uri('MyController#myMethod', {'foo': 'bar', 'id': 42})}` 

Therefore we implemented our own functionality. The `MvcUriBuilder` was exposed later so developers can use the same functionality from a controller. It was an addon. Using the JAX-RS `UriBuilder` would also work but I think the example should be:

```
URI uri = mvcContext.uriBuilder( "bookDetails" )  // @UriRef("bookDetails") on controller
         .resolveTemplate("isbn", 321321321312)   // @PathParam("isbn")
         .queryParam("lang", "de")                // @QueryParam("lang") (not replace!)
         .build();
```

We should be aware that the developer can use all the other methods like e.g. `UriBuilder#path(Class resource, String method)` too.

**Comment by chkal** [comment]
> Using the JAX-RS UriBuilder would also work but I think the example should be:

I agree. Sorry, my example wasn't actually correct.

> We should be aware that the developer can use all the other methods like e.g. UriBuilder#path(Class resource, String method) too.

I don't think that this is really a problem. We just need to document this accordingly.

To sum up: My vote goes for letting `MvcContext#uriBuilder()` return the standard JAX-RS `UriBuilder`.

**Comment by lefloh** [comment]
I agree. Here are the PRs:

* Spec: [#189](https://github.com/mvc-spec/mvc-spec/pull/189)
* Ozark: [#190](https://github.com/mvc-spec/ozark/pull/190)
