### ISSUE TITLE
Standardize org.eclipse.krazo.defaultViewFileExtension as javax.mvc.engine.defaultViewFileExtension

### ISSUE THREAD

**Issue by ngriffin7a** [mvc-spec/mvc-spec#213]
As discussed in a [related Google Groups thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jsr371-users/ovd9d1Lx3xA/SXS8IGVNFAAJ), I recommend that the `org.eclipse.krazo.defaultViewFileExtension` feature be standardized as `javax.mvc.engine.defaultViewFileExtension`.

**Comment by chkal** [comment]
Moved to https://github.com/eclipse-ee4j/mvc-api/issues/39
