### ISSUE TITLE
Idea: Standardized way to override HTTP methods in forms

### ISSUE THREAD

**Issue by erdlet** [mvc-spec/mvc-spec#219]
Hi all,

a few months ago, a feature to was added to Krazo which enables developers to override the HTTP method used in HTML forms by setting a hidden field that is evaluated while the request is processed. This way, developers can implement controllers which are using the full power of HTTP verbs what results in clearer and more understandable APIs.

Therefore I wanted to ask what you think about standardizing this functionality in the MVC API to ensure every person using an MVC implementation can profit from it. Also, this is something which nearly all MVC frameworks I know support (e.g. Spring MVC, Rails, Grails, Django) very successfully.

**Comment by chkal** [comment]
Thanks for creating this issue.

If this is a feature provided by most of the other MVC frameworks, we should definitely support it. And it should be more or less easy to do.

I'll assign this issue to "Future" so we can consider it for MVC 1.1.

**Comment by chkal** [comment]
Moved to: https://github.com/eclipse-ee4j/mvc-api/issues/39
