### ISSUE TITLE
Publish HTML-Version of the Spec

### ISSUE THREAD

**Issue by gtudan** [mvc-spec/mvc-spec#225]
It would be nice to have a HTML-Version of the spec, as it‘s easier to read on small screens. This might also help search engines to index the spec.

Since the spec is written in Asciidoctor and build with Travis this should be a quick win.

**Comment by chkal** [comment]
I like the idea. We already have automatic publishing of the TCK coverage reports. So maybe this is also easy to do?

https://github.com/mvc-spec/mvc-tck/blob/b53e78c0d782162a43fa393a4b351a07ba210906/.travis.yml#L12-L17
